Disabling search bar
inrupt/authorization-management-component pull request #12
Opened 2024-05-07 14:56 UTC by garciafdezpatricia

# Disable search Box

## Disabling search box when there are no access grants to show

## User testing instructions

## Commit checklist

- [ ] All acceptance criteria are met.
- [ ] Includes tests to ensure functionality, accessibility and prevent regressions, including E2E tests for supported browsers.
- [ ] Relevant documentation, if any, has been written/updated.
- [ ] The changelog has been updated, if applicable.
- [ ] A changeset version has been created, if applicable.
- [ ] Meets Inrupt coding standards and adheres to commit conventions.

## Design requirements checklist

- [ ] Meets Inrupt API Design and UX standards
- [ ] Is responsive to our documented minimum supported screen size + resolution
- [ ] Code is extensible by external contributors or anyone forking

2024-05-13 08:56 UTC, NSeydoux requested changes
I would prefer a different approach where the `ListAgentsWithVCs` component is given a more generic callback that takes as an argument the number of agents. The `useEffect` in `ListAgentsWithVCs` would keep the same dependency, and call that `onAgentUpdate` callback with the agent count (defaulting to 0). The logic to check if the agent count is zero could then be lifted into the `AuthenticatedRoute`.

2024-05-13 08:56 UTC, NSeydoux commented on src/components/ListAgents/ListAgentsWithVCs.tsx
> +    }
```suggestion
    if (agents !== undefined && agents.length > 0 && typeof onNotEmptyAgents === "function") {
        onNotEmptyAgents();
    }
```

2024-05-13 09:36 UTC, garciafdezpatricia commented on src/components/ListAgents/ListAgentsWithVCs.tsx
> +    }
Why is it better in this case to lift the check and disabling of the search bar to the `AuthenticatedRoute`? I thought that component was "responsible" of checking the authentication of the session and return the correct content in each case.

2024-05-13 12:44 UTC, NSeydoux commented on src/components/ListAgents/ListAgentsWithVCs.tsx
> +    }
As I understand the current architecture, `AuthenticatedRoute` is the component managing the display of the search bar. The reason I'm suggesting to lift the check up and have a more generic callback provided to `ListAgentsWithVCs` is because with the current approach, you can only have a trigger when there are agents. But if the parent needs to change its behavior if there are no agents, or even more specifically if there is a given number of agents (let's say you want to change display on a large number of agents compared to a few), you would not be able to do that because the current callback is hardcoded to non-zero.

2024-05-13 14:10 UTC, NSeydoux commented on src/components/ListAgents/ListAgentsWithVCs.tsx
> +    }
Replace all occurences opf `AutghenticatedRoute` by `index` because I don't know how to read github diffs anymore

2024-05-14 10:02 UTC, NSeydoux approved these changes
Some superficial suggestions, but overall looks good to me.

2024-05-14 10:02 UTC, NSeydoux commented on src/components/ListAgents/ListAgentsWithVCs.tsx
> +      onAgentUpdate(agentsCount);
```suggestion
      onAgentUpdate((agents ?? []).length);
```
I don't have a strong opinion on which one we should use, feel free to keep the one you find easier to read and understand.

2024-05-14 10:02 UTC, merged